# Hello Tensors

In [1]:
import numpy as np
import tensorflow as tf

### Tensors vs. Numpy Arrays

Tensors are types of arrays

In [2]:
# Numpy array
array = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

Convert an Array to a Tensor:

In [9]:
tensor = tf.convert_to_tensor(array) 
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

Access to Numpy array with .numpy() method

In [4]:
array2 = tensor.numpy()
array2

array([[1, 2, 3],
       [4, 5, 6]])

Tensors and Arrays share some attibutes, e.g. shape

In [6]:
array.shape

(2, 3)

In [7]:
tensor.shape

TensorShape([2, 3])

### Operations on Tensors

Element-wise operations

In [10]:
tensor*2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

Broadcasting rules apply

In [13]:
tensor*tf.constant([3,2,2], dtype=tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 3,  4,  6],
       [12, 10, 12]])>

### Additional Attributes & Methods

Find the tensor location

In [14]:
tensor.device

'/job:localhost/replica:0/task:0/device:CPU:0'

Move tensor to the GPU by calling tensor.gpu(), but needs GPU enabled

In [17]:
#tensor.gpu()